/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.text.MessageFormat;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import lojatds.controller.CompraController;
import lojatds.model.dao.DAOFactory;
import lojatds.model.dao.DatabaseException;

/**
 *
 * @author Rafa
 */
public class TelaRelatorioCompras extends javax.swing.JFrame implements Observer{
    
    private final CompraController controller;
    private CompraTableModel compraModel;
    /**
     * Creates new form TelaRelatorioCompras
     */
    public TelaRelatorioCompras(CompraController controller) {
        super("Relatório de compras");
        this.controller = controller;
        compraModel = new CompraTableModel();
        initComponents();
        jTableRelatorioCompras.setModel(compraModel);
        try {
            compraModel.updateCompras(controller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameRelatorioCompras = new javax.swing.JInternalFrame();
        jLabelRelatorioCompras = new javax.swing.JLabel();
        jButtonRelatorioComprasSim = new javax.swing.JButton();
        jButtonRelatorioComprasNao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorioCompras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrameRelatorioCompras.setVisible(true);

        jLabelRelatorioCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelatorioCompras.setText("Deseja imprimir relatório de compras?");

        jButtonRelatorioComprasSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/bullet_green.png"))); // NOI18N
        jButtonRelatorioComprasSim.setText("Sim");
        jButtonRelatorioComprasSim.setToolTipText("Imprimir relatório de compras");
        jButtonRelatorioComprasSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorioComprasSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioComprasSimActionPerformed(evt);
            }
        });

        jButtonRelatorioComprasNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/bullet_red.png"))); // NOI18N
        jButtonRelatorioComprasNao.setText("Não");
        jButtonRelatorioComprasNao.setToolTipText("Cancelar operação");
        jButtonRelatorioComprasNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorioComprasNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioComprasNaoActionPerformed(evt);
            }
        });

        jTableRelatorioCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorioCompras);

        javax.swing.GroupLayout jInternalFrameRelatorioComprasLayout = new javax.swing.GroupLayout(jInternalFrameRelatorioCompras.getContentPane());
        jInternalFrameRelatorioCompras.getContentPane().setLayout(jInternalFrameRelatorioComprasLayout);
        jInternalFrameRelatorioComprasLayout.setHorizontalGroup(
            jInternalFrameRelatorioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRelatorioComprasLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButtonRelatorioComprasSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRelatorioComprasNao)
                .addGap(114, 114, 114))
            .addGroup(jInternalFrameRelatorioComprasLayout.createSequentialGroup()
                .addGroup(jInternalFrameRelatorioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameRelatorioComprasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameRelatorioComprasLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabelRelatorioCompras)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jInternalFrameRelatorioComprasLayout.setVerticalGroup(
            jInternalFrameRelatorioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRelatorioComprasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelRelatorioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameRelatorioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRelatorioComprasSim)
                    .addComponent(jButtonRelatorioComprasNao))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameRelatorioCompras)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameRelatorioCompras)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelatorioComprasNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioComprasNaoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonRelatorioComprasNaoActionPerformed

    private void jButtonRelatorioComprasSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioComprasSimActionPerformed
        MessageFormat Header = new MessageFormat("Lista de compras");
        MessageFormat Footer = new MessageFormat("Page{0, number, integer}");
        try {
            jTableRelatorioCompras.print(JTable.PrintMode.NORMAL, Header, Footer);
            
        } catch(java.awt.print.PrinterException e) {
            System.err.format("Erro de impressão!", e.getMessage());
        }
    }//GEN-LAST:event_jButtonRelatorioComprasSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaGerenciarClientes().setVisible(true);
                DAOFactory dao = DAOFactory.getDAOFactory();
                CompraController controller = new CompraController(dao);
                TelaRelatorioCompras view = new TelaRelatorioCompras(controller);
                controller.addObserver(view);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioComprasNao;
    private javax.swing.JButton jButtonRelatorioComprasSim;
    private javax.swing.JInternalFrame jInternalFrameRelatorioCompras;
    private javax.swing.JLabel jLabelRelatorioCompras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorioCompras;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            System.out.println(controller.listar());
            compraModel.updateCompras(controller.listar());
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }
    }
}
