/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lojatds.controller.CompraController;
import lojatds.controller.FornecedorController;
import lojatds.controller.ProdutoController;
import lojatds.model.Compra;
import lojatds.model.Fornecedor;
import lojatds.model.Produto;
import lojatds.model.dao.DAOFactory;
import lojatds.model.dao.DatabaseException;

/**
 *
 * @author Rafa
 */
public class TelaEfetuarCompra extends javax.swing.JFrame implements Observer {

    FornecedorTableModel fornecedorModel = new FornecedorTableModel();
    private final FornecedorController fornecedorcontroller;
    ProdutoTableModel produtoModel = new ProdutoTableModel();
    private final ProdutoController produtocontroller;
    private final CompraController compracontroller;

    Compra compra = new Compra();

    /**
     * Creates new form TelaEfetuarCompra
     *
     * @param fornecedorcontroller
     * @param produtocontroller
     */
    public TelaEfetuarCompra(FornecedorController fornecedorcontroller, ProdutoController produtocontroller,
            CompraController compracontroller) {
        super("Efetuar compra");
        this.fornecedorcontroller = fornecedorcontroller;
        this.produtocontroller = produtocontroller;
        this.compracontroller = compracontroller;
        initComponents();
        jTableCompraFornecedor.setModel(fornecedorModel);
        jTableVendaProdutoCompraFornecedor.setModel(produtoModel);
        try {
            fornecedorModel.updateFornecedores(fornecedorcontroller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
        try {
            produtoModel.updateProdutos(produtocontroller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameCompraFornecedor = new javax.swing.JInternalFrame();
        jLabelCompraFornecedor = new javax.swing.JLabel();
        jTextFieldPesquisarCompraFornecedor = new javax.swing.JTextField();
        jButtonPesquisarCompraFornecedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompraFornecedor = new javax.swing.JTable();
        jLabelCodigoCompraFornecedor = new javax.swing.JLabel();
        jTextFieldCodigoCompraFornecedor = new javax.swing.JTextField();
        jLabelNomeCompraFornecedor = new javax.swing.JLabel();
        jTextFieldNomeCompraForneceodor = new javax.swing.JTextField();
        jSeparatorEfetuarVenda = new javax.swing.JSeparator();
        jLabelProdutoCompraFornecedor = new javax.swing.JLabel();
        jTextFieldPesquisarProdutoCompraFornecedor = new javax.swing.JTextField();
        jButtonPesquisarProdutoCompraFornecedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVendaProdutoCompraFornecedor = new javax.swing.JTable();
        jLabelCodigoProdutoCompraFornecedor = new javax.swing.JLabel();
        jTextFieldCodigoProduto = new javax.swing.JTextField();
        jLabelNomeProdutoCompraFornecedor = new javax.swing.JLabel();
        jTextFieldNomeProdutoCompraFornecedor = new javax.swing.JTextField();
        jSeparatorEfetuarVenda2 = new javax.swing.JSeparator();
        jLabelQuantidadeProdutoCompraFornecedor = new javax.swing.JLabel();
        jTextFieldQuantidadeProdutoCompraFornecedor = new javax.swing.JTextField();
        jLabelValorUnitarioCompraFornecedor = new javax.swing.JLabel();
        jTextFieldValorUnitarioCompraFornecedor = new javax.swing.JTextField();
        jLabelValorTotalCompraFornecedor = new javax.swing.JLabel();
        jTextFieldValorTotalCompraFornecedor = new javax.swing.JTextField();
        jButtonAdicionarCarrinhoCompraFornecedor = new javax.swing.JButton();
        jButtonCancelarCompraFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrameCompraFornecedor.setVisible(true);
        jInternalFrameCompraFornecedor.getContentPane().setLayout(null);

        jLabelCompraFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCompraFornecedor.setText("Fornecedor");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelCompraFornecedor);
        jLabelCompraFornecedor.setBounds(20, 10, 70, 20);
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldPesquisarCompraFornecedor);
        jTextFieldPesquisarCompraFornecedor.setBounds(20, 30, 270, 30);

        jButtonPesquisarCompraFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/search.png"))); // NOI18N
        jButtonPesquisarCompraFornecedor.setText("Pesquisar");
        jButtonPesquisarCompraFornecedor.setToolTipText("Pesquisar fornecedor");
        jButtonPesquisarCompraFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCompraFornecedorActionPerformed(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jButtonPesquisarCompraFornecedor);
        jButtonPesquisarCompraFornecedor.setBounds(300, 30, 120, 30);

        jTableCompraFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCompraFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCompraFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCompraFornecedor);

        jInternalFrameCompraFornecedor.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 690, 110);

        jLabelCodigoCompraFornecedor.setText("Código:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelCodigoCompraFornecedor);
        jLabelCodigoCompraFornecedor.setBounds(20, 200, 50, 14);

        jTextFieldCodigoCompraFornecedor.setEnabled(false);
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldCodigoCompraFornecedor);
        jTextFieldCodigoCompraFornecedor.setBounds(70, 190, 50, 30);

        jLabelNomeCompraFornecedor.setText("Fornecedor:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelNomeCompraFornecedor);
        jLabelNomeCompraFornecedor.setBounds(140, 200, 70, 14);

        jTextFieldNomeCompraForneceodor.setEnabled(false);
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldNomeCompraForneceodor);
        jTextFieldNomeCompraForneceodor.setBounds(210, 190, 320, 30);

        jSeparatorEfetuarVenda.setToolTipText("");
        jSeparatorEfetuarVenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparatorEfetuarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparatorEfetuarVenda.setName(""); // NOI18N
        jInternalFrameCompraFornecedor.getContentPane().add(jSeparatorEfetuarVenda);
        jSeparatorEfetuarVenda.setBounds(10, 10, 710, 220);

        jLabelProdutoCompraFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProdutoCompraFornecedor.setText("Produto");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelProdutoCompraFornecedor);
        jLabelProdutoCompraFornecedor.setBounds(20, 240, 60, 20);
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldPesquisarProdutoCompraFornecedor);
        jTextFieldPesquisarProdutoCompraFornecedor.setBounds(20, 260, 270, 30);

        jButtonPesquisarProdutoCompraFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/search.png"))); // NOI18N
        jButtonPesquisarProdutoCompraFornecedor.setText("Pesquisar");
        jButtonPesquisarProdutoCompraFornecedor.setToolTipText("Pesquisar produto");
        jButtonPesquisarProdutoCompraFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarProdutoCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarProdutoCompraFornecedorActionPerformed(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jButtonPesquisarProdutoCompraFornecedor);
        jButtonPesquisarProdutoCompraFornecedor.setBounds(300, 260, 120, 30);

        jTableVendaProdutoCompraFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVendaProdutoCompraFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVendaProdutoCompraFornecedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVendaProdutoCompraFornecedor);

        jInternalFrameCompraFornecedor.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 310, 690, 100);

        jLabelCodigoProdutoCompraFornecedor.setText("Código:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelCodigoProdutoCompraFornecedor);
        jLabelCodigoProdutoCompraFornecedor.setBounds(20, 430, 50, 14);

        jTextFieldCodigoProduto.setEnabled(false);
        jTextFieldCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProdutoActionPerformed(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldCodigoProduto);
        jTextFieldCodigoProduto.setBounds(70, 420, 50, 30);

        jLabelNomeProdutoCompraFornecedor.setText("Produto:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelNomeProdutoCompraFornecedor);
        jLabelNomeProdutoCompraFornecedor.setBounds(170, 430, 50, 14);

        jTextFieldNomeProdutoCompraFornecedor.setEnabled(false);
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldNomeProdutoCompraFornecedor);
        jTextFieldNomeProdutoCompraFornecedor.setBounds(220, 420, 300, 30);

        jSeparatorEfetuarVenda2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrameCompraFornecedor.getContentPane().add(jSeparatorEfetuarVenda2);
        jSeparatorEfetuarVenda2.setBounds(10, 240, 710, 230);

        jLabelQuantidadeProdutoCompraFornecedor.setText("Quantidade:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelQuantidadeProdutoCompraFornecedor);
        jLabelQuantidadeProdutoCompraFornecedor.setBounds(20, 490, 70, 14);

        jTextFieldQuantidadeProdutoCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeProdutoCompraFornecedorActionPerformed(evt);
            }
        });
        jTextFieldQuantidadeProdutoCompraFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeProdutoCompraFornecedorKeyReleased(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldQuantidadeProdutoCompraFornecedor);
        jTextFieldQuantidadeProdutoCompraFornecedor.setBounds(90, 480, 60, 30);

        jLabelValorUnitarioCompraFornecedor.setText("Valor unitário:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelValorUnitarioCompraFornecedor);
        jLabelValorUnitarioCompraFornecedor.setBounds(170, 490, 80, 14);

        jTextFieldValorUnitarioCompraFornecedor.setEnabled(false);
        jTextFieldValorUnitarioCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorUnitarioCompraFornecedorActionPerformed(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldValorUnitarioCompraFornecedor);
        jTextFieldValorUnitarioCompraFornecedor.setBounds(250, 480, 60, 30);

        jLabelValorTotalCompraFornecedor.setText("Valor total:");
        jInternalFrameCompraFornecedor.getContentPane().add(jLabelValorTotalCompraFornecedor);
        jLabelValorTotalCompraFornecedor.setBounds(380, 490, 60, 14);

        jTextFieldValorTotalCompraFornecedor.setEnabled(false);
        jInternalFrameCompraFornecedor.getContentPane().add(jTextFieldValorTotalCompraFornecedor);
        jTextFieldValorTotalCompraFornecedor.setBounds(440, 480, 60, 30);

        jButtonAdicionarCarrinhoCompraFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/cart_add.png"))); // NOI18N
        jButtonAdicionarCarrinhoCompraFornecedor.setText("Adicionar ao carrinho");
        jButtonAdicionarCarrinhoCompraFornecedor.setToolTipText("Confirmar compra");
        jButtonAdicionarCarrinhoCompraFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarCarrinhoCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarCarrinhoCompraFornecedorActionPerformed(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jButtonAdicionarCarrinhoCompraFornecedor);
        jButtonAdicionarCarrinhoCompraFornecedor.setBounds(90, 550, 180, 30);

        jButtonCancelarCompraFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/cancel.png"))); // NOI18N
        jButtonCancelarCompraFornecedor.setText("Cancelar Compra");
        jButtonCancelarCompraFornecedor.setToolTipText("Cancelar compra");
        jButtonCancelarCompraFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelarCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCompraFornecedorActionPerformed(evt);
            }
        });
        jInternalFrameCompraFornecedor.getContentPane().add(jButtonCancelarCompraFornecedor);
        jButtonCancelarCompraFornecedor.setBounds(410, 550, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrameCompraFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCompraFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(761, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCompraFornecedorActionPerformed
        try {
            fornecedorModel.updateFornecedores(fornecedorcontroller.pesquisar(jTextFieldPesquisarCompraFornecedor.getText()));
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaGerenciarFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarCompraFornecedorActionPerformed

    private void jTextFieldCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProdutoActionPerformed

    private void jButtonCancelarCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCompraFornecedorActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarCompraFornecedorActionPerformed

    private void jTableCompraFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompraFornecedorMouseClicked
        try {
            produtoModel.updateProdutos(produtocontroller.listar());
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaEfetuarCompra.class.getName()).log(Level.SEVERE, null, ex);
        }

        int linha = jTableCompraFornecedor.getSelectedRow();
        Fornecedor ev = fornecedorModel.getFornecedor(linha);
        jTextFieldCodigoCompraFornecedor.setText("" + ev.getCodigo());

        jTextFieldNomeCompraForneceodor.setText(ev.getNome());

        compra.setFornecedor(ev);
    }//GEN-LAST:event_jTableCompraFornecedorMouseClicked

    private void jTableVendaProdutoCompraFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVendaProdutoCompraFornecedorMouseClicked

        int linha = jTableVendaProdutoCompraFornecedor.getSelectedRow();
        Produto ev = produtoModel.getProduto(linha);
        jTextFieldCodigoProduto.setText("" + ev.getCodigo());
        jTextFieldNomeProdutoCompraFornecedor.setText(ev.getNome());
        jTextFieldValorUnitarioCompraFornecedor.setText(String.valueOf(ev.getPrecoDeCompra()));
    }//GEN-LAST:event_jTableVendaProdutoCompraFornecedorMouseClicked

    private void jButtonAdicionarCarrinhoCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarCarrinhoCompraFornecedorActionPerformed
        if (jTextFieldCodigoCompraFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fornecedor necessário!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jTextFieldCodigoProduto.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Produto necessário!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (jTextFieldQuantidadeProdutoCompraFornecedor.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Quantidade necessária!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                }

                Produto prod = produtoModel.getProduto(jTableVendaProdutoCompraFornecedor.getSelectedRow());
                prod.setQuantidade(Integer.parseInt(jTextFieldQuantidadeProdutoCompraFornecedor.getText()));
                
                compra.addProduto(prod);

                float total = 0;
                for (Produto p : compra.getLista()) {
                    total = (p.getPrecoDeCompra() * p.getQuantidade()) + total;
                }

                compra.setTotal(total);
                jTextFieldQuantidadeProdutoCompraFornecedor.setText("");
                jTextFieldValorTotalCompraFornecedor.setText("" + compra.getTotal());
                new TelaCarrinhoDeCompras(compra, compracontroller).setVisible(true);

            }
        }
    }//GEN-LAST:event_jButtonAdicionarCarrinhoCompraFornecedorActionPerformed

    private void jButtonPesquisarProdutoCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarProdutoCompraFornecedorActionPerformed
        try {
            produtoModel.updateProdutos(produtocontroller.pesquisar(jTextFieldPesquisarProdutoCompraFornecedor.getText()));
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaGerenciarProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarProdutoCompraFornecedorActionPerformed

    private void jTextFieldValorUnitarioCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorUnitarioCompraFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorUnitarioCompraFornecedorActionPerformed

    private void jTextFieldQuantidadeProdutoCompraFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeProdutoCompraFornecedorKeyReleased
        float total = 0;
        total = (Float.parseFloat(jTextFieldValorUnitarioCompraFornecedor.getText())
                * Float.parseFloat(jTextFieldQuantidadeProdutoCompraFornecedor.getText())) + compra.getTotal();

        jTextFieldValorTotalCompraFornecedor.setText(String.valueOf(total));
    }//GEN-LAST:event_jTextFieldQuantidadeProdutoCompraFornecedorKeyReleased

    private void jTextFieldQuantidadeProdutoCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeProdutoCompraFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidadeProdutoCompraFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                DAOFactory dao = DAOFactory.getDAOFactory();
                FornecedorController fornecedorcontroller = new FornecedorController(dao);
                ProdutoController produtocontroller = new ProdutoController(dao);

                CompraController compracontroller = new CompraController(dao);
                TelaEfetuarCompra view = new TelaEfetuarCompra(fornecedorcontroller, produtocontroller, compracontroller);
                fornecedorcontroller.addObserver(view);
                produtocontroller.addObserver(view);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarCarrinhoCompraFornecedor;
    private javax.swing.JButton jButtonCancelarCompraFornecedor;
    private javax.swing.JButton jButtonPesquisarCompraFornecedor;
    private javax.swing.JButton jButtonPesquisarProdutoCompraFornecedor;
    private javax.swing.JInternalFrame jInternalFrameCompraFornecedor;
    private javax.swing.JLabel jLabelCodigoCompraFornecedor;
    private javax.swing.JLabel jLabelCodigoProdutoCompraFornecedor;
    private javax.swing.JLabel jLabelCompraFornecedor;
    private javax.swing.JLabel jLabelNomeCompraFornecedor;
    private javax.swing.JLabel jLabelNomeProdutoCompraFornecedor;
    private javax.swing.JLabel jLabelProdutoCompraFornecedor;
    private javax.swing.JLabel jLabelQuantidadeProdutoCompraFornecedor;
    private javax.swing.JLabel jLabelValorTotalCompraFornecedor;
    private javax.swing.JLabel jLabelValorUnitarioCompraFornecedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparatorEfetuarVenda;
    private javax.swing.JSeparator jSeparatorEfetuarVenda2;
    private javax.swing.JTable jTableCompraFornecedor;
    private javax.swing.JTable jTableVendaProdutoCompraFornecedor;
    private javax.swing.JTextField jTextFieldCodigoCompraFornecedor;
    private javax.swing.JTextField jTextFieldCodigoProduto;
    private javax.swing.JTextField jTextFieldNomeCompraForneceodor;
    private javax.swing.JTextField jTextFieldNomeProdutoCompraFornecedor;
    private javax.swing.JTextField jTextFieldPesquisarCompraFornecedor;
    private javax.swing.JTextField jTextFieldPesquisarProdutoCompraFornecedor;
    private javax.swing.JTextField jTextFieldQuantidadeProdutoCompraFornecedor;
    private javax.swing.JTextField jTextFieldValorTotalCompraFornecedor;
    private javax.swing.JTextField jTextFieldValorUnitarioCompraFornecedor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            System.out.println(fornecedorcontroller.listar());
            fornecedorModel.updateFornecedores(fornecedorcontroller.listar());
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }

        try {
            System.out.println(produtocontroller.listar());
            produtoModel.updateProdutos(produtocontroller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }
}
