/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.text.MessageFormat;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import lojatds.controller.FornecedorController;
import lojatds.model.dao.DAOFactory;
import lojatds.model.dao.DatabaseException;

/**
 *
 * @author Rafa
 */
public class TelaRelatorioFornecedores extends javax.swing.JFrame implements Observer {
    
    private final FornecedorController controller;
    private FornecedorTableModel fornecedorModel;
    /**
     * Creates new form TelaRelatorioFornecedores
     */
    public TelaRelatorioFornecedores(FornecedorController controller) {
        super("Relatório de fornecedores");
        this.controller = controller;
        fornecedorModel = new FornecedorTableModel();
        initComponents();
        jTableRelatorioFornecedores.setModel(fornecedorModel);
        try {
            fornecedorModel.updateFornecedores(controller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameRelatorioFornecedores = new javax.swing.JInternalFrame();
        jLabelRelatorioFornecedores = new javax.swing.JLabel();
        jButtonRelatorioFornecedoresSim = new javax.swing.JButton();
        jButtonRelatorioFornecedoresNao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorioFornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrameRelatorioFornecedores.setVisible(true);

        jLabelRelatorioFornecedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelatorioFornecedores.setText("Deseja imprimir relatório de fornecedores?");

        jButtonRelatorioFornecedoresSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/bullet_green.png"))); // NOI18N
        jButtonRelatorioFornecedoresSim.setText("Sim");
        jButtonRelatorioFornecedoresSim.setToolTipText("Imprimir relatório de fornecedores");
        jButtonRelatorioFornecedoresSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorioFornecedoresSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioFornecedoresSimActionPerformed(evt);
            }
        });

        jButtonRelatorioFornecedoresNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/bullet_red.png"))); // NOI18N
        jButtonRelatorioFornecedoresNao.setText("Não");
        jButtonRelatorioFornecedoresNao.setToolTipText("Cancelar operação");
        jButtonRelatorioFornecedoresNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorioFornecedoresNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioFornecedoresNaoActionPerformed(evt);
            }
        });

        jTableRelatorioFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorioFornecedores);

        javax.swing.GroupLayout jInternalFrameRelatorioFornecedoresLayout = new javax.swing.GroupLayout(jInternalFrameRelatorioFornecedores.getContentPane());
        jInternalFrameRelatorioFornecedores.getContentPane().setLayout(jInternalFrameRelatorioFornecedoresLayout);
        jInternalFrameRelatorioFornecedoresLayout.setHorizontalGroup(
            jInternalFrameRelatorioFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRelatorioFornecedoresLayout.createSequentialGroup()
                .addGroup(jInternalFrameRelatorioFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameRelatorioFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrameRelatorioFornecedoresLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrameRelatorioFornecedoresLayout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(jLabelRelatorioFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameRelatorioFornecedoresLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButtonRelatorioFornecedoresSim)
                        .addGap(207, 207, 207)
                        .addComponent(jButtonRelatorioFornecedoresNao)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jInternalFrameRelatorioFornecedoresLayout.setVerticalGroup(
            jInternalFrameRelatorioFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRelatorioFornecedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRelatorioFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameRelatorioFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRelatorioFornecedoresNao)
                    .addComponent(jButtonRelatorioFornecedoresSim))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameRelatorioFornecedores, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameRelatorioFornecedores, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(799, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelatorioFornecedoresNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioFornecedoresNaoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonRelatorioFornecedoresNaoActionPerformed

    private void jButtonRelatorioFornecedoresSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioFornecedoresSimActionPerformed
        MessageFormat Header = new MessageFormat("Lista de fornecedores");
        MessageFormat Footer = new MessageFormat("Page{0, number, integer}");
        try {
            jTableRelatorioFornecedores.print(JTable.PrintMode.NORMAL, Header, Footer);
            
        } catch(java.awt.print.PrinterException e) {
            System.err.format("Erro de impressão!", e.getMessage());
        }
    }//GEN-LAST:event_jButtonRelatorioFornecedoresSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feejInternalFrameRelatorioFornecedores(optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaGerenciarClientes().setVisible(true);
                DAOFactory dao = DAOFactory.getDAOFactory();
                FornecedorController controller = new FornecedorController(dao);
                TelaRelatorioFornecedores view = new TelaRelatorioFornecedores(controller);
                controller.addObserver(view);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioFornecedoresNao;
    private javax.swing.JButton jButtonRelatorioFornecedoresSim;
    private javax.swing.JInternalFrame jInternalFrameRelatorioFornecedores;
    private javax.swing.JLabel jLabelRelatorioFornecedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorioFornecedores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            System.out.println(controller.listar());
            fornecedorModel.updateFornecedores(controller.listar());
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }
    }
}
