/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import net.proteanit.sql.DbUtils;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lojatds.controller.ClienteController;
import lojatds.model.Cliente;
import lojatds.model.dao.DAOFactory;
import lojatds.model.dao.DatabaseException;
import lojatds.model.dao.jdbc.ConnectionFactory;
import lojatds.model.dao.jdbc.JDBCClienteDAO;

/**
 *
 * @author Rafa
 */
public class TelaGerenciarClientes extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form TelaGerenciarClientes
     */
    private final ClienteController controller;
    private ClienteTableModel clienteModel;
    private static Connection conn;

    public TelaGerenciarClientes(ClienteController controller) {
        super("Gerenciar Clientes");
        this.controller = controller;
        clienteModel = new ClienteTableModel();
        initComponents();
        jTableClientes.setModel(clienteModel);
        try {
            clienteModel.updateClientes(controller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameCliente = new javax.swing.JInternalFrame();
        jTextFieldPesquisarCliente = new javax.swing.JTextField();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelCodigoCliente = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jLabelNomeCliente = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabelCpfCliente = new javax.swing.JLabel();
        jLabelTelefoneCliente = new javax.swing.JLabel();
        jLabelCepCliente = new javax.swing.JLabel();
        jFormattedTextFieldCpfCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefoneCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCepCliente = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogradouroCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCidadeCliente = new javax.swing.JTextField();
        jLabelUfCliente = new javax.swing.JLabel();
        jButtonNovoCliente = new javax.swing.JButton();
        jButtonEditarCliente = new javax.swing.JButton();
        jButtonExcluirCliente = new javax.swing.JButton();
        jButtonLimparCliente = new javax.swing.JButton();
        jComboBoxUfCliente = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrameCliente.setVisible(true);

        jTextFieldPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarClienteKeyReleased(evt);
            }
        });

        jButtonPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/search.png"))); // NOI18N
        jButtonPesquisarCliente.setText("Pesquisar");
        jButtonPesquisarCliente.setToolTipText("Pesquisar cliente");
        jButtonPesquisarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jLabelCodigoCliente.setText("Código:");

        jTextFieldCodigoCliente.setEnabled(false);

        jLabelNomeCliente.setText("Nome:");

        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });

        jLabelCpfCliente.setText("CPF:");

        jLabelTelefoneCliente.setText("Telefone:");

        jLabelCepCliente.setText("CEP:");

        try {
            jFormattedTextFieldCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCpfClienteActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Logradouro:");

        jLabel2.setText("Cidade:");

        jTextFieldCidadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeClienteActionPerformed(evt);
            }
        });

        jLabelUfCliente.setText("UF:");

        jButtonNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/user_add.png"))); // NOI18N
        jButtonNovoCliente.setText("Novo");
        jButtonNovoCliente.setToolTipText("Cadastrar novo cliente");
        jButtonNovoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });

        jButtonEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/user_edit.png"))); // NOI18N
        jButtonEditarCliente.setText("Editar");
        jButtonEditarCliente.setToolTipText("Editar cliente");
        jButtonEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClienteActionPerformed(evt);
            }
        });

        jButtonExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/user_delete.png"))); // NOI18N
        jButtonExcluirCliente.setText("Excluir");
        jButtonExcluirCliente.setToolTipText("Excluir cliente");
        jButtonExcluirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClienteActionPerformed(evt);
            }
        });

        jButtonLimparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/DeleteGrey.png"))); // NOI18N
        jButtonLimparCliente.setText("Limpar");
        jButtonLimparCliente.setToolTipText("Limpar campos");
        jButtonLimparCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparClienteActionPerformed(evt);
            }
        });

        jComboBoxUfCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        javax.swing.GroupLayout jInternalFrameClienteLayout = new javax.swing.GroupLayout(jInternalFrameCliente.getContentPane());
        jInternalFrameCliente.getContentPane().setLayout(jInternalFrameClienteLayout);
        jInternalFrameClienteLayout.setHorizontalGroup(
            jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(274, 274, 274))
                    .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                        .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                        .addComponent(jLabelCodigoCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabelNomeCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNomeCliente))
                                    .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameClienteLayout.createSequentialGroup()
                                                        .addComponent(jLabelCepCliente)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jFormattedTextFieldCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameClienteLayout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTextFieldCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameClienteLayout.createSequentialGroup()
                                                        .addComponent(jLabelCpfCliente)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jFormattedTextFieldCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                                .addComponent(jButtonNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                                .addComponent(jLabelTelefoneCliente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFormattedTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabelUfCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldLogradouroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxUfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButtonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jButtonExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addComponent(jButtonLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jInternalFrameClienteLayout.setVerticalGroup(
            jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameClienteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoCliente)
                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpfCliente)
                    .addComponent(jLabelTelefoneCliente)
                    .addComponent(jFormattedTextFieldCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCepCliente)
                    .addComponent(jFormattedTextFieldCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLogradouroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUfCliente)
                    .addComponent(jComboBoxUfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jInternalFrameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCliente)
        );

        setSize(new java.awt.Dimension(776, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCidadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeClienteActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        if (jTextFieldNomeCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome é um campo obrigatório.");
            jTextFieldNomeCliente.requestFocus();
        } else {
            if (jFormattedTextFieldCpfCliente.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "CPF é um campo obrigatório.");
                jFormattedTextFieldCpfCliente.requestFocus();
            } else if (JOptionPane.showConfirmDialog(this, "Deseja cadastrar o cliente?",
                    "Cadastrar cliente", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.OK_OPTION) {

                Cliente cliente = new Cliente();
                cliente.setNome(jTextFieldNomeCliente.getText());
                cliente.setCPF(jFormattedTextFieldCpfCliente.getText());
                cliente.setTelefone(jFormattedTextFieldTelefoneCliente.getText());
                cliente.setCEP(jFormattedTextFieldCepCliente.getText());
                cliente.setLogradouro(jTextFieldLogradouroCliente.getText());
                cliente.setCidade(jTextFieldCidadeCliente.getText());
                cliente.setUF((String) jComboBoxUfCliente.getSelectedItem());
                //cliente.setCodigo(Integer.parseInt(jTextFieldCodigoCliente.getText()));

                try {
                    controller.cadastrar(cliente);
                    JOptionPane.showMessageDialog(this, "Cliente registrado com sucesso!");
                    jTextFieldCodigoCliente.setText("");
                    jTextFieldNomeCliente.setText("");
                    jFormattedTextFieldCpfCliente.setText("");
                    jFormattedTextFieldTelefoneCliente.setText("");
                    jTextFieldCidadeCliente.setText("");
                    jTextFieldLogradouroCliente.setText("");
                    jFormattedTextFieldCepCliente.setText("");

                } catch (DatabaseException ex) {
                    Logger.getLogger(TelaGerenciarClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        try {
            clienteModel.updateClientes(controller.pesquisar(jTextFieldPesquisarCliente.getText())); 
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaGerenciarClientes.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        int linha = jTableClientes.getSelectedRow();
        Cliente ev = clienteModel.getCliente(linha);
        jTextFieldCodigoCliente.setText("" + ev.getCodigo());
        jTextFieldNomeCliente.setText(ev.getNome());
        jFormattedTextFieldCpfCliente.setText(ev.getCPF());
        jFormattedTextFieldTelefoneCliente.setText(ev.getTelefone());
        jTextFieldCidadeCliente.setText(ev.getCidade());
        jTextFieldLogradouroCliente.setText(ev.getLogradouro());
        jFormattedTextFieldCepCliente.setText(ev.getCEP());
        jComboBoxUfCliente.setSelectedItem(ev.getUF());
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jButtonLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparClienteActionPerformed
        jTextFieldCodigoCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedTextFieldCpfCliente.setText("");
        jFormattedTextFieldTelefoneCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jTextFieldLogradouroCliente.setText("");
        jFormattedTextFieldCepCliente.setText("");
    }//GEN-LAST:event_jButtonLimparClienteActionPerformed

    private void jButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClienteActionPerformed
        Cliente cliente = new Cliente();
        cliente.setNome(jTextFieldNomeCliente.getText());
        cliente.setCPF(jFormattedTextFieldCpfCliente.getText());
        cliente.setTelefone(jFormattedTextFieldTelefoneCliente.getText());
        cliente.setCEP(jFormattedTextFieldCepCliente.getText());
        cliente.setLogradouro(jTextFieldLogradouroCliente.getText());
        cliente.setCidade(jTextFieldCidadeCliente.getText());
        cliente.setUF((String) jComboBoxUfCliente.getSelectedItem());
        cliente.setCodigo(Integer.parseInt(jTextFieldCodigoCliente.getText()));

        try {
            controller.atualizar(cliente);
            JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");

        } catch (DatabaseException ex) {
            Logger.getLogger(TelaGerenciarClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEditarClienteActionPerformed

    private void jButtonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClienteActionPerformed
        try {
            int codigo = Integer.parseInt(jTextFieldCodigoCliente.getText());
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente remover o cliente?",
                    "Excluir cliente", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.OK_OPTION) {
                if (controller.excluir(codigo)) {
                    JOptionPane.showMessageDialog(this, "Cliente removido com sucesso!");
                    jTextFieldCodigoCliente.setText("");
                    jTextFieldNomeCliente.setText("");
                    jFormattedTextFieldCpfCliente.setText("");
                    jFormattedTextFieldTelefoneCliente.setText("");
                    jTextFieldCidadeCliente.setText("");
                    jTextFieldLogradouroCliente.setText("");
                    jFormattedTextFieldCepCliente.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha");
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Código Inválido.");
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirClienteActionPerformed

    private void jTextFieldPesquisarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarClienteKeyReleased
        try {
            clienteModel.updateClientes(controller.pesquisar(jTextFieldPesquisarCliente.getText())); 
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaGerenciarClientes.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jTextFieldPesquisarClienteKeyReleased

    private void jFormattedTextFieldCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCpfClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaGerenciarClientes().setVisible(true);
                DAOFactory dao = DAOFactory.getDAOFactory();
                ClienteController controller = new ClienteController(dao);
                TelaGerenciarClientes view = new TelaGerenciarClientes(controller);
                controller.addObserver(view);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarCliente;
    private javax.swing.JButton jButtonExcluirCliente;
    private javax.swing.JButton jButtonLimparCliente;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JComboBox jComboBoxUfCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneCliente;
    private javax.swing.JInternalFrame jInternalFrameCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCepCliente;
    private javax.swing.JLabel jLabelCodigoCliente;
    private javax.swing.JLabel jLabelCpfCliente;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelTelefoneCliente;
    private javax.swing.JLabel jLabelUfCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldCidadeCliente;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldLogradouroCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPesquisarCliente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            System.out.println(controller.listar());
            clienteModel.updateClientes(controller.listar());
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }
    }
}
