/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lojatds.controller.ProdutoController;
import lojatds.model.Produto;
import lojatds.model.dao.DAOFactory;
import lojatds.model.dao.DatabaseException;

/**
 *
 * @author Rafa
 */
public class TelaEstoqueAtual extends javax.swing.JFrame implements Observer {

    private final ProdutoController controller;
    private ProdutoTableModel produtoModel;
    
    /**
     * Creates new form TelaEstoqueAtual
     * @param controller
     */
    public TelaEstoqueAtual(ProdutoController controller) {
        super("Estoque atual");
        this.controller = controller;
        produtoModel = new ProdutoTableModel();
        initComponents();
        jTableEntradaDeProdutos.setModel(produtoModel);
        try {
            produtoModel.updateProdutos(controller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTextFieldEntradaDeProdutosPesquisa = new javax.swing.JTextField();
        jButtonEntradaDeProdutosPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntradaDeProdutos = new javax.swing.JTable();
        jLabelCodigoEntradaDeProdutos = new javax.swing.JLabel();
        jTextFieldEstoqueAtual = new javax.swing.JTextField();
        jLabelProdutoEntradaDeProdutos = new javax.swing.JLabel();
        jTextFieldProdutoEstoqueAtual = new javax.swing.JTextField();
        jLabelQuantidadeEstoqueAtual = new javax.swing.JLabel();
        jTextFieldTotalEstoqueAtual = new javax.swing.JTextField();
        jSeparatorCodigoEntradaDeProdutos = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(jTextFieldEntradaDeProdutosPesquisa);
        jTextFieldEntradaDeProdutosPesquisa.setBounds(40, 70, 280, 30);

        jButtonEntradaDeProdutosPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/search.png"))); // NOI18N
        jButtonEntradaDeProdutosPesquisa.setText("Pesquisar");
        jButtonEntradaDeProdutosPesquisa.setToolTipText("Pesquisar produto no estoque");
        jButtonEntradaDeProdutosPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntradaDeProdutosPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntradaDeProdutosPesquisaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonEntradaDeProdutosPesquisa);
        jButtonEntradaDeProdutosPesquisa.setBounds(330, 70, 110, 30);

        jTableEntradaDeProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEntradaDeProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEntradaDeProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEntradaDeProdutos);

        jInternalFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 550, 110);

        jLabelCodigoEntradaDeProdutos.setText("Código:");
        jInternalFrame1.getContentPane().add(jLabelCodigoEntradaDeProdutos);
        jLabelCodigoEntradaDeProdutos.setBounds(50, 260, 50, 14);

        jTextFieldEstoqueAtual.setEnabled(false);
        jInternalFrame1.getContentPane().add(jTextFieldEstoqueAtual);
        jTextFieldEstoqueAtual.setBounds(100, 250, 59, 30);

        jLabelProdutoEntradaDeProdutos.setText("Produto:");
        jInternalFrame1.getContentPane().add(jLabelProdutoEntradaDeProdutos);
        jLabelProdutoEntradaDeProdutos.setBounds(250, 260, 50, 14);

        jTextFieldProdutoEstoqueAtual.setEnabled(false);
        jInternalFrame1.getContentPane().add(jTextFieldProdutoEstoqueAtual);
        jTextFieldProdutoEstoqueAtual.setBounds(300, 250, 230, 30);

        jLabelQuantidadeEstoqueAtual.setText("Estoque Atual:");
        jInternalFrame1.getContentPane().add(jLabelQuantidadeEstoqueAtual);
        jLabelQuantidadeEstoqueAtual.setBounds(50, 300, 80, 14);

        jTextFieldTotalEstoqueAtual.setEnabled(false);
        jInternalFrame1.getContentPane().add(jTextFieldTotalEstoqueAtual);
        jTextFieldTotalEstoqueAtual.setBounds(140, 290, 40, 30);

        jSeparatorCodigoEntradaDeProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrame1.getContentPane().add(jSeparatorCodigoEntradaDeProdutos);
        jSeparatorCodigoEntradaDeProdutos.setBounds(30, 30, 570, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(650, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntradaDeProdutosPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntradaDeProdutosPesquisaActionPerformed
        try {
            produtoModel.updateProdutos(controller.pesquisar(jTextFieldEntradaDeProdutosPesquisa.getText()));
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaGerenciarProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEntradaDeProdutosPesquisaActionPerformed

    private void jTableEntradaDeProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEntradaDeProdutosMouseClicked
        int linha = jTableEntradaDeProdutos.getSelectedRow();
        Produto ev = produtoModel.getProduto(linha);
        jTextFieldEstoqueAtual.setText("" + ev.getCodigo());
        jTextFieldProdutoEstoqueAtual.setText(ev.getNome());
        jTextFieldTotalEstoqueAtual.setText(String.valueOf(ev.getQuantidade()));
    }//GEN-LAST:event_jTableEntradaDeProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAOFactory dao = DAOFactory.getDAOFactory();
                ProdutoController controller = new ProdutoController(dao);
                TelaEstoqueAtual view = new TelaEstoqueAtual(controller);
                controller.addObserver(view);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntradaDeProdutosPesquisa;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelCodigoEntradaDeProdutos;
    private javax.swing.JLabel jLabelProdutoEntradaDeProdutos;
    private javax.swing.JLabel jLabelQuantidadeEstoqueAtual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorCodigoEntradaDeProdutos;
    private javax.swing.JTable jTableEntradaDeProdutos;
    private javax.swing.JTextField jTextFieldEntradaDeProdutosPesquisa;
    private javax.swing.JTextField jTextFieldEstoqueAtual;
    private javax.swing.JTextField jTextFieldProdutoEstoqueAtual;
    private javax.swing.JTextField jTextFieldTotalEstoqueAtual;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            System.out.println(controller.listar());
            produtoModel.updateProdutos(controller.listar());
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }
    }
}
