/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lojatds.controller.CompraController;
import lojatds.model.Compra;
import lojatds.model.Produto;
import lojatds.model.dao.DatabaseException;

/**
 *
 * @author Rafa
 */
public class TelaCarrinhoDeCompras extends javax.swing.JFrame {

    private Compra compra;
    ProdutoTableModel produtoModel = new ProdutoTableModel();
    private final CompraController compracontroller;

    /**
     * Creates new form TelaCarrinhoDeCompras
     */
    public TelaCarrinhoDeCompras(Compra c,CompraController compracontroller) {
        super("Carrinho de compras");
        this.compra = c;
        this.compracontroller = compracontroller;
        
        initComponents();
        jTextFieldValorTotalCarrinhoCompras.setText(String.valueOf(compra.getTotal()));
        jTextFieldComprasFornecedor.setText(compra.getFornecedor().getNome());
        jTableCarrinhoDeCompras.setModel(produtoModel);
        produtoModel.updateProdutos(compra.getLista());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameCarrinhoDeCompras = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarrinhoDeCompras = new javax.swing.JTable();
        jLabelCarrinhosDeComprasCompras = new javax.swing.JLabel();
        jButtonConfimarCompra = new javax.swing.JButton();
        jButtonExcluirProdutoCarrinhoCompras = new javax.swing.JButton();
        jTextFieldComprasFornecedor = new javax.swing.JTextField();
        jLabelFornecedorCarrinhoDeCompras = new javax.swing.JLabel();
        jLabelValorTotalCarrinhoDeCompras = new javax.swing.JLabel();
        jTextFieldValorTotalCarrinhoCompras = new javax.swing.JTextField();
        jSeparatorCarrinhoDeCompras = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrameCarrinhoDeCompras.setVisible(true);
        jInternalFrameCarrinhoDeCompras.getContentPane().setLayout(null);

        jTableCarrinhoDeCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCarrinhoDeCompras);

        jInternalFrameCarrinhoDeCompras.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 490, 140);

        jLabelCarrinhosDeComprasCompras.setText("Carrinho de compras");
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jLabelCarrinhosDeComprasCompras);
        jLabelCarrinhosDeComprasCompras.setBounds(50, 30, 120, 14);

        jButtonConfimarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/accept.png"))); // NOI18N
        jButtonConfimarCompra.setText("Confirmar compra");
        jButtonConfimarCompra.setToolTipText("Confirmar compra");
        jButtonConfimarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfimarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfimarCompraActionPerformed(evt);
            }
        });
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jButtonConfimarCompra);
        jButtonConfimarCompra.setBounds(80, 270, 150, 30);

        jButtonExcluirProdutoCarrinhoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/delete.png"))); // NOI18N
        jButtonExcluirProdutoCarrinhoCompras.setText("Excluir do carrinho");
        jButtonExcluirProdutoCarrinhoCompras.setToolTipText("Excluir item do carrinho");
        jButtonExcluirProdutoCarrinhoCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirProdutoCarrinhoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProdutoCarrinhoComprasActionPerformed(evt);
            }
        });
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jButtonExcluirProdutoCarrinhoCompras);
        jButtonExcluirProdutoCarrinhoCompras.setBounds(340, 270, 150, 30);

        jTextFieldComprasFornecedor.setEnabled(false);
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jTextFieldComprasFornecedor);
        jTextFieldComprasFornecedor.setBounds(110, 210, 110, 30);

        jLabelFornecedorCarrinhoDeCompras.setText("Fornecedor:");
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jLabelFornecedorCarrinhoDeCompras);
        jLabelFornecedorCarrinhoDeCompras.setBounds(40, 210, 70, 14);

        jLabelValorTotalCarrinhoDeCompras.setText("Valor total da venda:");
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jLabelValorTotalCarrinhoDeCompras);
        jLabelValorTotalCarrinhoDeCompras.setBounds(270, 210, 110, 14);

        jTextFieldValorTotalCarrinhoCompras.setEnabled(false);
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jTextFieldValorTotalCarrinhoCompras);
        jTextFieldValorTotalCarrinhoCompras.setBounds(390, 210, 120, 30);

        jSeparatorCarrinhoDeCompras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrameCarrinhoDeCompras.getContentPane().add(jSeparatorCarrinhoDeCompras);
        jSeparatorCarrinhoDeCompras.setBounds(20, 10, 530, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrameCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirProdutoCarrinhoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProdutoCarrinhoComprasActionPerformed
        compra.removerProduto(produtoModel.getProduto(jTableCarrinhoDeCompras.getSelectedRow()));
        jTableCarrinhoDeCompras.setModel(produtoModel);
        produtoModel.updateProdutos(compra.getLista());
    }//GEN-LAST:event_jButtonExcluirProdutoCarrinhoComprasActionPerformed

    private void jButtonConfimarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfimarCompraActionPerformed
        try {
            compracontroller.cadastrar(compra);
            compra.getLista().removeAll(compra.getLista());
            JOptionPane.showMessageDialog(null, "Compra realizada com sucesso!");
            dispose();
            
        } catch (DatabaseException ex) {
            Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConfimarCompraActionPerformed

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //new TelaCarrinhoDeCompras(new Compra(),).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfimarCompra;
    private javax.swing.JButton jButtonExcluirProdutoCarrinhoCompras;
    private javax.swing.JInternalFrame jInternalFrameCarrinhoDeCompras;
    private javax.swing.JLabel jLabelCarrinhosDeComprasCompras;
    private javax.swing.JLabel jLabelFornecedorCarrinhoDeCompras;
    private javax.swing.JLabel jLabelValorTotalCarrinhoDeCompras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorCarrinhoDeCompras;
    private javax.swing.JTable jTableCarrinhoDeCompras;
    private javax.swing.JTextField jTextFieldComprasFornecedor;
    private javax.swing.JTextField jTextFieldValorTotalCarrinhoCompras;
    // End of variables declaration//GEN-END:variables
}
