/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojatds.view;

import java.text.MessageFormat;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import lojatds.controller.VendaController;
import lojatds.model.dao.DAOFactory;
import lojatds.model.dao.DatabaseException;

/**
 *
 * @author Rafa
 */
public class TelaRelatorioVendas extends javax.swing.JFrame implements Observer {
    
    private final VendaController controller;
    private VendaTableModel vendaModel;
    /**
     * Creates new form TelaRelatorioVendas
     */
    public TelaRelatorioVendas(VendaController controller) {
        super("Relatório de vendas");
        this.controller = controller;
        vendaModel = new VendaTableModel();
        initComponents();
        jTableRelatorioVendas.setModel(vendaModel);
        try {
            vendaModel.updateVendas(controller.listar());
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameRelatorioVendas = new javax.swing.JInternalFrame();
        jLabelRelatorioVendas = new javax.swing.JLabel();
        jButtonRelatorioVendasSim = new javax.swing.JButton();
        jButtonRelatorioVendasNao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorioVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrameRelatorioVendas.setVisible(true);

        jLabelRelatorioVendas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelatorioVendas.setText("Deseja imprimir relatório de vendas?");

        jButtonRelatorioVendasSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/bullet_green.png"))); // NOI18N
        jButtonRelatorioVendasSim.setText("Sim");
        jButtonRelatorioVendasSim.setToolTipText("Imprimir relatório de vendas");
        jButtonRelatorioVendasSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorioVendasSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioVendasSimActionPerformed(evt);
            }
        });

        jButtonRelatorioVendasNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojatds/view/imagens/bullet_red.png"))); // NOI18N
        jButtonRelatorioVendasNao.setText("Não");
        jButtonRelatorioVendasNao.setToolTipText("Cancelar operação");
        jButtonRelatorioVendasNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorioVendasNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioVendasNaoActionPerformed(evt);
            }
        });

        jTableRelatorioVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorioVendas);

        javax.swing.GroupLayout jInternalFrameRelatorioVendasLayout = new javax.swing.GroupLayout(jInternalFrameRelatorioVendas.getContentPane());
        jInternalFrameRelatorioVendas.getContentPane().setLayout(jInternalFrameRelatorioVendasLayout);
        jInternalFrameRelatorioVendasLayout.setHorizontalGroup(
            jInternalFrameRelatorioVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameRelatorioVendasLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButtonRelatorioVendasSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRelatorioVendasNao)
                .addGap(138, 138, 138))
            .addGroup(jInternalFrameRelatorioVendasLayout.createSequentialGroup()
                .addGroup(jInternalFrameRelatorioVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameRelatorioVendasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameRelatorioVendasLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabelRelatorioVendas)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jInternalFrameRelatorioVendasLayout.setVerticalGroup(
            jInternalFrameRelatorioVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRelatorioVendasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRelatorioVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameRelatorioVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRelatorioVendasNao)
                    .addComponent(jButtonRelatorioVendasSim))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameRelatorioVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameRelatorioVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelatorioVendasNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioVendasNaoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonRelatorioVendasNaoActionPerformed

    private void jButtonRelatorioVendasSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioVendasSimActionPerformed
        MessageFormat Header = new MessageFormat("Lista de vendas");
        MessageFormat Footer = new MessageFormat("Page{0, number, integer}");
        try {
            jTableRelatorioVendas.print(JTable.PrintMode.NORMAL, Header, Footer);
            
        } catch(java.awt.print.PrinterException e) {
            System.err.format("Erro de impressão!", e.getMessage());
        }
    }//GEN-LAST:event_jButtonRelatorioVendasSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaGerenciarClientes().setVisible(true);
                DAOFactory dao = DAOFactory.getDAOFactory();
                VendaController controller = new VendaController(dao);
                TelaRelatorioVendas view = new TelaRelatorioVendas(controller);
                controller.addObserver(view);
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioVendasNao;
    private javax.swing.JButton jButtonRelatorioVendasSim;
    private javax.swing.JInternalFrame jInternalFrameRelatorioVendas;
    private javax.swing.JLabel jLabelRelatorioVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorioVendas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            System.out.println(controller.listar());
            vendaModel.updateVendas(controller.listar());
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco: " + e.getMessage());
        }
    }
}
